version: '3.8'

services:
  postiz:
    image: ghcr.io/gitroomhq/postiz-app:latest
    container_name: postiz
    restart: always
    env_file:
      - .env
    environment:
      MAIN_URL: "${MAIN_URL}"
      FRONTEND_URL: "${FRONTEND_URL}"
      NEXT_PUBLIC_BACKEND_URL: "${NEXT_PUBLIC_BACKEND_URL}/api"
      DATABASE_URL: "${DATABASE_URL}"
      REDIS_URL: "redis://postiz-redis:6379"
      BACKEND_INTERNAL_URL: "${BACKEND_INTERNAL_URL}"
      IS_GENERAL: "${IS_GENERAL}" # Required for self-hosting.
      JWT_SECRET: "${JWT_SECRET}"
      
      # Storage Configuration
      STORAGE_PROVIDER: "${STORAGE_PROVIDER}"
      UPLOAD_DIRECTORY: "${UPLOAD_DIRECTORY}"
      NEXT_PUBLIC_UPLOAD_DIRECTORY: "${NEXT_PUBLIC_UPLOAD_DIRECTORY}"
      
      # Email Configuration (Resend)
      EMAIL_PROVIDER: "${EMAIL_PROVIDER}"
      RESEND_API_KEY: "${RESEND_API_KEY}"
      EMAIL_FROM_NAME: "${EMAIL_FROM_NAME}"
      EMAIL_FROM_ADDRESS: "${EMAIL_FROM_ADDRESS}"
      
      # Social Media Configuration
      X_API_KEY: "${X_API_KEY}"
      X_API_SECRET: "${X_API_SECRET}"
      BLUESKY_IDENTIFIER: "${BLUESKY_IDENTIFIER}"
      BLUESKY_PASSWORD: "${BLUESKY_PASSWORD}"
    volumes:
      - postiz-config:/config/
      - "${UPLOAD_PATH}"
    ports:
      - "${POSTIZ_PORT}:${POSTIZ_PORT}"
    networks:
      - postiz-network
    depends_on:
      postiz-postgres:
        condition: service_healthy
      postiz-redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${POSTIZ_PORT}/api/health"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 30s

  postiz-postgres:
    image: postgres:17-alpine
    container_name: postiz-postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - postiz-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "5432:5432"  # Exposed for local development

  postiz-redis:
    image: redis:7.2-alpine
    container_name: postiz-redis
    restart: always
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - postiz-redis-data:/data
    networks:
      - postiz-network
    ports:
      - "6379:6379"  # Exposed for local development

volumes:
  postgres-volume:
    external: false
  postiz-redis-data:
    external: false
  postiz-config:
    external: false

networks:
  postiz-network:
    external: false
